# Server 설정
server:
  port: 1111
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 6h

# MySQL 및 JPA 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anything?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: bbsk3939!@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # n + 1 문제 해결, in절로 쿼리 실행
        default_batch_fetch_size: 10
  devtools:
    # Auto Restart
    restart:
      enabled: true
  config:
    import: env.yml

# Logging 설정
logging.level:
  org.hibernate.orm.jdbc.bind: trace
  root: info
  org:
    springframework:
      cache: TRACE;

# Chrome Driver
mysender:
  chrome:
    driver: classpath:chromedriver
