# local
spring:
  config:
    activate:
      on-profile: local
  devtools:
    # Auto Restart
    restart:
      enabled: true
  # Gmail:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Server 설정
server:
  port: 1111
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 6h

# Logging 설정
logging.level:
  org.hibernate.orm.jdbc.bind: trace
  root: info
  org:
    springframework:
      cache: TRACE;

# Chrome Driver
mysender:
  chrome:
    driver:
      path: classpath:chromedriver

---

# prod
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    # Auto Restart
    restart:
      enabled: true
  # Gmail:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Server 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 6h

# Logging 설정
logging.level:
  org.hibernate.orm.jdbc.bind: trace
  root: info
  org:
    springframework:
      cache: TRACE;

# Chrome Driver
mysender:
  chrome:
    driver:
      path: classpath:chromedriver